### ISSUE TITLE
Improve contract security

### ISSUE THREAD

**Issue by chrismaree** [registreerocks/funding_contract#1]
Verify sender is valid student ownership contract and check signing of message corresponds to claimed uport address that owns the ownership contract.

**Comment by sabineschaller** [comment]
I don't think that is necessary. The contract is called from the owner, i.e. the university (account0) and students can invoke these endpoints by using the API. This should be enough security. The student contracts and the students don't have any funds to invoke the contract in the beginning anyways.

**Comment by chrismaree** [comment]
But if I break into the API I can steal all our ETH. This is fine for beta though. But we will need to change this when we go to the main net. But I suspect that our design will change a lot before then so lets shelf this for now.

**Comment by sabineschaller** [comment]
We will hopefully have a completely different flow in the future, e.g. delegated calls.
